- name: My information
  hosts: local
  connection: local # for localhosts
  vars:
    name : "Nanda Raju" #string
    age: 29 #number
    practice: #list
    - Linux
    - Shell
    - Ansible
    - Terraform
    - AWS
    - K8
    working: true #boolean
    tools: #map/dictionary
      ci: jenkins # string
      cm: ansible
      cloud: aws
      aws:
      - IAM
      - S3
  tasks:
  - name: print my information
    ansible.builtin.debug:
      msg: "Hi, I am {{ name }}, with age: {{ age }}, practice on: {{ practice }}, and working: {{ working }}, tools are: {{ tools }}"