- name: variables to print
  hosts: web
  # vars:
  #   NAME: "Nanda"
  # AGE: 29
  # LIVING: "London"
  # vars_files:
  # - vars.yaml
  # vars_prompt:
  # - name: NAME
  #   prompt: Please enter the name
  #   private: false # not confidential
  tasks:
  - name: print the information
    vars:
      #COURSE: "DevOps with AWS from TASK level"
      NAME: "Raj"
      AGE: 29
      LIVING: "India"
    ansible.builtin.debug:
      msg: "Hi name is : {{NAME}}, Age is: {{AGE}}, living in: {{LIVING}}"

#1. command line/args
#2. Task level
#3. Files
#4. prompt
#5. Play
#6. inventory
#7. Roles