- name: variables from files
  hosts: web
  vars_prompt:
  - name: NAME
    prompt: Please enter the name
    private: false #not confidential
  - name: AGE
    prompt: Please enter the age
    private: true # confidential
  - name: LIVING
    prompt: Please enter the location where you living
    private: false #not confidential
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi name is : {{NAME}}, Age is: {{AGE}}, living in: {{LIVING}}"